/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_morihirosoft_mediacodectest16_MainActivity */

#ifndef _Included_jp_morihirosoft_mediacodectest16_MainActivity
#define _Included_jp_morihirosoft_mediacodectest16_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_morihirosoft_mediacodectest16_MainActivity_DEBUG
#define jp_morihirosoft_mediacodectest16_MainActivity_DEBUG 0L
/*
 * Class:     jp_morihirosoft_mediacodectest16_MainActivity
 * Method:    native_init
 * Signature: (ZIII[I)I
 */
JNIEXPORT jint JNICALL Java_jp_morihirosoft_mediacodectest16_MainActivity_native_1init
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jintArray);

/*
 * Class:     jp_morihirosoft_mediacodectest16_MainActivity
 * Method:    native_quit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_morihirosoft_mediacodectest16_MainActivity_native_1quit
  (JNIEnv *, jclass);

/*
 * Class:     jp_morihirosoft_mediacodectest16_MainActivity
 * Method:    native_draw
 * Signature: ([B[II[B)I
 */
JNIEXPORT jint JNICALL Java_jp_morihirosoft_mediacodectest16_MainActivity_native_1draw
  (JNIEnv *, jclass, jbyteArray, jintArray, jint, jbyteArray);

/*
 * Class:     jp_morihirosoft_mediacodectest16_MainActivity
 * Method:    native_cnvavc
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_morihirosoft_mediacodectest16_MainActivity_native_1cnvavc
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
